---
- name: 'Install apt-transport-https'
  apt:
    name: 'apt-transport-https'

- name: 'Add the docker apt signing key'
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    state: 'present'
  notify: 'docker-apt-get-update'

- name: 'Add the official docker repo'
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release|lower}} stable'
    state: 'present'
  notify: 'docker-apt-get-update'

- meta: flush_handlers
